### ISSUE TITLE
File leakage

### ISSUE THREAD

**Issue by amiles347** [cornetp/eagle-owl#15]
You have the fclose on the .live file inside of the check data integrity if statement.  This means that you slowly build up a load of open files every time there is a data issue.  This continues into the OS file limit is reached and then the program stops being able to write data to the SQL db.  Move the fclose outside of the if statement and all should be fixed.

Andy

**Comment by cornetp** [comment]
You're right, I just fixed it.
Thanks for your contribution.

Philippe
