### ISSUE TITLE
0 month since end of January

### ISSUE THREAD

**Issue by calibx** [cornetp/eagle-owl#18]
Hi,

Since one month and a half the cm160 process display : 
LIVE: 08/00/2016 19:47 : 3236.100000 W
LIVE: 08/00/2016 19:52 : 869.400000 W
LIVE: 08/00/2016 19:52 : 853.300000 W
LIVE: 08/00/2016 19:53 : 1400.700000 W
LIVE: 08/00/2016 19:53 : 1368.500000 W
LIVE: 08/00/2016 19:53 : 1416.800000 W

But on the LCD screen the month is well set to March.
Any idea ?

Regards

**Comment by Egorkat** [comment]
On 08.03.2016 21:08, calibx wrote:

> Hi,
> 
> Since one month and a half the cm160 process display :
> LIVE: 08/00/2016 19:47 : 3236.100000 W
> LIVE: 08/00/2016 19:52 : 869.400000 W
> LIVE: 08/00/2016 19:52 : 853.300000 W
> LIVE: 08/00/2016 19:53 : 1400.700000 W
> LIVE: 08/00/2016 19:53 : 1368.500000 W
> LIVE: 08/00/2016 19:53 : 1416.800000 W
> 
> But on the LCD screen the month is well set to March.
> Any idea ?
> 
> Regards
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cornetp/eagle-owl/issues/18.
> 
> Hello!

Had same issue also in first days of March. Resolved via full reset for 
cm160 receiver.
Then had some fun with sqlite3 command line tool to fix 0 month :-)

Good luck!

**Comment by calibx** [comment]
Hi,

Thank you ! It works like a charm !
The full reset is decribe here : https://theowl.zendesk.com/hc/en-gb/articles/201284913-CM160-OWL-USB-full-reset-pairing-process
